version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    parallelism: 5
    docker:
      - image: cimg/python:3.11
    resource_class: small  
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests (in parallel)
          command: |
            set -e
            TEST_FILES=$(circleci tests glob "*_test.py")
            mkdir -p test-results
            echo "$TEST_FILES" | circleci tests run \
            --command="xargs pytest -o junit_family=legacy --junitxml=test-results/junit.xml" \
            --verbose --split-by=timings
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-results

workflows:
  sample:
    jobs:
      - build-and-test